---
image: "YOUR_HAZELCAST_IMAGE:TAG"
imagePullPolicy: "Always"
# Enter the number of initial members in Hazelcast cluster.
replicas: 3
# Setting below to true will deploy the infinity in client-server Hazelcast model.
# Note: Make sure to set this value as "false" in case of platform version below "8.6". If not set this will fail the installation.
enabled: true
# username to be used in client-server Hazelcast model for authentication
username: ""
# password to be used in client-server Hazelcast model for authentication
password: ""

# Memory and CPU settings for HZ service
resources:
  requests:
    memory: "1Gi"
    cpu: 1
  limits:
    memory: "1Gi"
    cpu: 2
# client settings for Hazelcast
client:
  clusterName: "PRPC"
# Server side settings for Hazelcast
server:
  java_opts: "-Xms820m -Xmx820m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/hazelcast/logs/heapdump.hprof
  -XX:+UseParallelGC -Xlog:gc*,gc+phases=debug:file=/opt/hazelcast/logs/gc.log:time,pid,tags:filecount=5,filesize=3m"
  jmx_enabled: "true"
  health_monitoring_level: "OFF"
  operation_generic_thread_count: ""
  operation_thread_count: ""
  io_thread_count: ""
  event_thread_count: ""
  max_join_seconds: ""
  group_name: "PRPC"
  mancenter_url: ""
  graceful_shutdown_max_wait_seconds: "600"
  service_dns_timeout: ""
  logging_level: "info"
  diagnostics_enabled: "true"
  diagnostics_metric_level: "info"
  diagnostic_log_file_size_mb: "50"
  diagnostics_file_count: "3"
