{{ if (eq (include "customArtifactorySSLVerificationEnabled" .) "true") }}
{{- if .Values.global.customArtifactory.certificate }}
{{- include "pegaCustomArtifactoryCertificatesConfigTemplate" . }}
{{- end }}
{{- end }}