{{ if .Values.enabled }}
---
{{- if (semverCompare ">= 1.21.0-0" (trimPrefix "v" .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "srs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "srs.srs-service.labels" . | indent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
  {{- include "srs.srs-service.match-labels" . | indent 6 }}
{{ end }}
